print (myname + " Can i ask you a favor?")
print('you have to say yes')
myanswer = input ()
print ("thank you for answering , " +myanswer)
print ("the length of your answer is :")
print (len(myanswer))
print("what is your address?")
myaddress = input ()
print ("you will be getting a package for your help at " + myaddress)
int ("you will be getting a package for your help at " + myaddress)
